import zfit
import numpy as np
from landau_pdf import trunc_landau
import tensorflow as tf
import pickle as pkl

# Generate THEO X EXP pdf from input components
# THEO component comes from lineshapes_in, which should be a dict of form {name : source,...}
# where source may be a .pkl file with a np.histogram; a np.histogram; or a .txt file with a list of p,pdf values
# These are used to generate a single histogram PDF representing a ProdPDF of the components
# EXP components come from fitpars_in, which should be a dict of form
# {name : {'pdf' : pdftype, 'params' : pars_in},...}
# pars_in may be a .pkl file containing a dictionary of form {p_bin : {parN_restype : {},...},...}
# or a dictionary generated by res_component of form {p_bin : {parN_restype : zfit.Parameter,...},...}
# These components will be convolved, together with the THEO pdf, to give the total pdf.

def load_lineshape(lineshape_in,name,binedges=None):
    if isinstance(lineshape_in,str):
        if lineshape_in.endswith('.pkl'):
            lineshape = pkl.load(open(lineshape_in,'rb'))
            print(f'Loaded lineshape for {name} as pickle!')
            if isinstance(lineshape,tuple):
                return lineshape
            else:
                return np.histogram(lineshape,binedges)
        else:
            vals = []
            cents = []
            with open(lineshape_in,'r') as f:
                for line in f.readlines():
                    parts = line.split()
                    cents.append(float(parts[0]))
                    vals.append(float(parts[1]))
            print(f'Loaded lineshape for {name} as .txt/tbl file!')
            edges = [(a+b)/2 for a,b in zip(cents[:-1],cents[1:])]
            low  = cents[0] -(edges[0]-cents[0])
            edges.insert(0,low)
            high = cents[-1]+(cents[-1]-edges[-1])
            edges.append(high)
            return (np.array(vals),np.array(edges))
    else:
        return lineshape_in

def gen_theo_exp(fitpars_in, lineshapes_in) -> dict:

    if len(lineshapes_in) == 1:
        prob,edges = load_lineshape(lineshapes_in.values()[0],lineshapes_in.keys()[0])
    elif sorted(lineshapes_in.keys()) == ['eff','theo']:
        p_theo, e_theo = load_lineshape(lineshapes_in['theo'],'theo')
        e_theo = np.round(e_theo,decimals=2)
        p_eff,  e_eff  = load_lineshape(lineshapes_in['eff'],'eff')
        e_eff = np.round(e_eff,decimals=2)
        e_all = np.unique(np.append(e_theo,e_eff))
        e_all = e_all[(e_all-e_theo[0]>=-0.01)&(e_all-e_theo[-1]<=0.01)]
        b_theo = 0
        b_eff = 0
        p_mult = []
        for e in e_all[:-1]:
            if b_theo < len(p_theo)-1 and abs(e-e_theo[b_theo+1])<0.01: b_theo += 1
            if b_eff  < len(p_eff)-1  and abs(e-e_eff[b_eff+1])<0.01:   b_eff += 1
            p_mult.append(p_theo[b_theo]*p_eff[b_eff])
        prob = np.array(p_mult)
        edges = e_all
    else:
        print("Currently supporting a single lineshape or separate 'theo' and 'eff' lineshapes. Exiting...")
        exit()

    # Process parameters for experimental components
    fitpars_out = {'info' : {}, 'lineshape' : (prob,edges)}
    for comp in fitpars_in.keys():
        fitpars_comp = fitpars_in[comp].copy()
        fitpars_out['info'][comp] = fitpars_comp.pop('info',None)
        fitpars_out.update(fitpars_comp)

    return fitpars_out

def make_HistogramPDF(prob,edges):
    class myHistogramPDF(zfit.pdf.ZPDF):
        _N_OBS = 1
        _PARAMS = []
        _PROB = tf.reshape(tf.constant(prob),      [len(prob),1])
        _LOW  = tf.reshape(tf.constant(edges[:-1]),[len(prob),1])
        _HIGH = tf.reshape(tf.constant(edges[1:]), [len(prob),1])
        
        def _unnormalized_pdf(self, x):
            x = zfit.z.unstack_x(x)
            return tf.reduce_sum(tf.where((x >= self._LOW) & (x < self._HIGH),self._PROB,0),0)
    return myHistogramPDF

def doConv(true_pdf, obs_gen, obs_res, name, info, zpars):

    obs_conv = zfit.Space('x',float(obs_gen.v1.lower-obs_res.v1.lower),float(obs_gen.v1.upper-obs_res.v1.upper))
    obs_full = zfit.Space('x',float(obs_gen.v1.lower+obs_res.v1.lower),float(obs_gen.v1.upper+obs_res.v1.upper))

    binwidth_eval = 0.1
    nbins_gen = int((obs_gen.v1.upper - obs_gen.v1.lower)/binwidth_eval)
    nbins_res = int((obs_res.v1.upper - obs_res.v1.lower)/binwidth_eval)
    
    pdfs = []
    fracs = []

    p_bins = [p_bin for p_bin in info['p_bins'] if p_bin[1] > float(obs_gen.v1.lower)+0.0001 and p_bin[0] < float(obs_gen.v1.upper)-0.0001]
    pdf = info['pdf']
    
    for ip,pbin in enumerate(p_bins):
        plow  = float(obs_gen.v1.lower) if ip == 0 else pbin[0]
        phigh = float(obs_gen.v1.upper) if ip == len(p_bins)-1 else pbin[1]
        obs_slice = zfit.Space('x',plow,phigh)
        if isinstance(true_pdf,tuple):
            prob,edges = true_pdf
            pfilt = (edges>=plow)&(edges<phigh)
            efilt = (edges>=plow)&(edges<=phigh)
            my_hist = make_HistogramPDF(prob[pfilt[:-1]],edges[efilt])
            norm = sum(prob[pfilt[:-1]]*(edges[efilt][1:]-edges[efilt][:-1]))
            fracs.append(norm)
            true_pdf_slice = my_hist(obs=obs_gen)
        elif len(p_bins) == 1:
            true_pdf_slice = true_pdf
        else:
            norm = float(true_pdf.integrate(limits=obs_slice, norm=False))
            fracs.append(norm)
            true_pdf_slice = zfit.pdf.TruncatedPDF(true_pdf,limits=obs_slice,obs=obs_gen)

        # Get res pdf
        if pdf == "landau":
            res_pdf = trunc_landau(obs=obs_res, loc=zpars[f'loc{ip}_{name}'], scale=zpars[f'scale{ip}_{name}'])
        elif pdf == "gcb":
            res_pdf = zfit.pdf.GeneralizedCB(obs=obs_res, mu=zpars[f'mu{ip}_{name}'], sigmal=zpars[f'sigmaL{ip}_{name}'], sigmar=zpars[f'sigmaR{ip}_{name}'], alphal=zpars[f'alphaL{ip}_{name}'], alphar=zpars[f'alphaR{ip}_{name}'], nl=zpars[f'nL{ip}_{name}'], nr=zpars[f'nR{ip}_{name}'])
        else:
            print('ERROR: only gcb and landau PDFs are supported for experimental effects. Exiting...')
            exit()

        func   = true_pdf_slice if (nbins_gen >= nbins_res) else res_pdf
        kernel = res_pdf        if (nbins_gen >= nbins_res) else true_pdf_slice
        nbins_kern = min(nbins_res, nbins_gen)
        conv = zfit.pdf.FFTConvPDFV1(func, kernel, n=nbins_kern, obs=obs_conv, norm=obs_full)
        pdfs.append(conv)

    if len(pdfs) > 1:
        pdf_sum = zfit.pdf.SumPDF(pdfs, fracs=[f/sum(fracs) for f in fracs], obs=obs_conv, norm=obs_full)
    else:
        pdf_sum = pdfs[0]
    
    return pdf_sum

